include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - vaultexplorer-i18n-wip/**
    - lib/l10n/generated/**
    - build/**
    - android/**
linter:
  rules:
    avoid_print: true
    unawaited_futures: true