import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:vaultexplorer/core/api/vault_file_io_api.dart';
import 'package:vaultexplorer/core/api/vault_hash_api.dart';
import 'package:vaultexplorer/data/models/mounted_container.dart';
import 'package:vaultexplorer/features/tools/models/hash_verifier_models.dart';
import 'package:vaultexplorer/features/tools/models/tool_models.dart';
import 'package:vaultexplorer/features/tools/services/hash_verifier_service.dart';

class _FakeHashApi extends VaultHashApi {
  _FakeHashApi(this.fileBytes) : super(const MethodChannel('test'));

  final Uint8List fileBytes;
  final Map<int, Map<String, List<int>>> _sessions = {};
  final List<int> discardedOpIds = [];
  final List<int> finishedOpIds = [];

  @override
  Future<void> beginHashSession(int opId, List<String> algorithms) async {
    _sessions[opId] = {for (final a in algorithms) a: <int>[]};
  }

  @override
  Future<void> updateHashSession(int opId, Uint8List bytes) async {
    final session = _sessions[opId];
    if (session == null) throw StateError('updateHashSession with no open session');
    for (final buf in session.values) {
      buf.addAll(bytes);
    }
  }

  @override
  Future<Map<String, String>> finishHashSession(int opId) async {
    final session = _sessions.remove(opId);
    if (session == null) throw StateError('finishHashSession with no open session');
    finishedOpIds.add(opId);
    return session.map((algo, bytes) => MapEntry(algo, _fakeDigest(bytes)));
  }

  @override
  Future<void> discardHashSession(int opId) async {
    _sessions.remove(opId);
    discardedOpIds.add(opId);
  }

  String _fakeDigest(List<int> bytes) {
    var acc = bytes.length;
    for (final b in bytes) {
      acc = (acc * 31 + b) & 0x7fffffff;
    }
    return acc.toRadixString(16).padLeft(8, '0');
  }
}

MountedContainer _container() => MountedContainer(
      uri: 'file:///test.vault',
      displayName: 'Test Vault',
      volId: 1,
      rootFiles: const [],
      mountedAt: DateTime(2026, 1, 1),
      totalSpace: 100000000,
      freeSpace: 50000000,
    );

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('HashVerifierService.parseManifest', () {
    test('parses GNU coreutils text-mode lines and infers algorithm from hex length', () {
      const manifest = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.txt\n'
          '9e107d9d372bb6826bd81d3542a419d6  other.bin\n';
      final entries = HashVerifierService().parseManifest(manifest);

      expect(entries, hasLength(2));
      expect(entries[0].algorithm, equals(HashAlgorithm.sha256));
      expect(entries[0].fileName, equals('file.txt'));
      expect(entries[1].algorithm, equals(HashAlgorithm.md5));
    });

    test('parses BSD-tagged lines using the explicit algorithm tag', () {
      const manifest = 'SHA256 (archive.zip) = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n';
      final entries = HashVerifierService().parseManifest(manifest);

      expect(entries, hasLength(1));
      expect(entries.single.algorithm, equals(HashAlgorithm.sha256));
      expect(entries.single.fileName, equals('archive.zip'));
    });

    test('skips blank lines and comments', () {
      const manifest = '# generated by sha256sum\n'
          '\n'
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.txt\n';
      final entries = HashVerifierService().parseManifest(manifest);
      expect(entries, hasLength(1));
    });

    test('an empty manifest produces no entries', () {
      final entries = HashVerifierService().parseManifest('');
      expect(entries, isEmpty);
    });
  });
}