import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:vaultexplorer/core/api/vault_file_io_api.dart';
import 'package:vaultexplorer/core/api/vault_hash_api.dart';
import 'package:vaultexplorer/core/api/vault_engine_events.dart';
import 'package:vaultexplorer/features/tools/models/hash_verifier_models.dart';
import 'package:vaultexplorer/features/tools/services/hash_verifier_service.dart';
import 'package:vaultexplorer/features/tools/services/vault_file_scanner.dart';

HashVerifierService _service() {
  final fileIoApi = VaultFileIoApi(const MethodChannel('test/file-io'));
  return HashVerifierService(
    hashApi: VaultHashApi(const MethodChannel('test/hash')),
    fileIoApi: fileIoApi,
    engineEvents: VaultEngineEvents(),
    scanner: VaultFileScanner(fileIoApi),
  );
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('HashVerifierService.parseManifest', () {
    test('parses GNU coreutils text-mode lines and infers algorithm from hex length', () {
      const manifest = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.txt\n'
          '9e107d9d372bb6826bd81d3542a419d6  other.bin\n';
      final entries = _service().parseManifest(manifest);

      expect(entries, hasLength(2));
      expect(entries[0].algorithm, equals(HashAlgorithm.sha256));
      expect(entries[0].fileName, equals('file.txt'));
      expect(entries[1].algorithm, equals(HashAlgorithm.md5));
    });

    test('parses BSD-tagged lines using the explicit algorithm tag', () {
      const manifest = 'SHA256 (archive.zip) = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\n';
      final entries = _service().parseManifest(manifest);

      expect(entries, hasLength(1));
      expect(entries.single.algorithm, equals(HashAlgorithm.sha256));
      expect(entries.single.fileName, equals('archive.zip'));
    });

    test('skips blank lines and comments', () {
      const manifest = '# generated by sha256sum\n'
          '\n'
          'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  file.txt\n';
      final entries = _service().parseManifest(manifest);
      expect(entries, hasLength(1));
    });

    test('an empty manifest produces no entries', () {
      final entries = _service().parseManifest('');
      expect(entries, isEmpty);
    });
  });
}
