#!/usr/bin/env bash
# Builds the minified pdf.js viewer bundle from source and drops it into
# android/app/src/main/assets/pdfjs/. Invoked automatically by
# android/app/build.gradle.kts (preBuild).
set -euo pipefail

cd "$(dirname "$0")/.."   # repo root

PDFJS_TAG="v6.2.108"
PDFJS_REPO="https://github.com/mozilla/pdf.js.git"
OUT_DIR="android/app/src/main/assets/pdfjs"
SRC_DIR="/tmp/pdfjs-src-${PDFJS_TAG}"

# --- Idempotency: skip if output already exists ---
# Set FORCE_REBUILD_PDFJS=1 to bypass this, e.g. when doing reproducibility
# testing on a checkout that's already built pdf.js once before -- otherwise
# a stale local bundle from a previous run keeps getting reused silently,
# which defeats the point of comparing a fresh build against another
# environment's.
if [ -f "$OUT_DIR/pdf.min.mjs" ] && [ -f "$OUT_DIR/pdf.worker.min.mjs" ] && [ "${FORCE_REBUILD_PDFJS:-0}" != "1" ]; then
  echo "pdf.js already built at $OUT_DIR, skipping (set FORCE_REBUILD_PDFJS=1, or delete pdf.min.mjs, to force a rebuild)."
  exit 0
fi

command -v node >/dev/null 2>&1 || { echo "error: node.js is required to build pdf.js from source" >&2; exit 1; }
command -v npm  >/dev/null 2>&1 || { echo "error: npm is required to build pdf.js from source" >&2; exit 1; }

if [ ! -d "$SRC_DIR" ]; then
  echo "Cloning pdf.js ${PDFJS_TAG}..."
  git clone --branch "$PDFJS_TAG" --depth 1 "$PDFJS_REPO" "$SRC_DIR"
fi

echo "Building pdf.js minified bundle (npm ci && npx gulp minified)..."
(cd "$SRC_DIR" && npm ci && npx gulp minified)

BUILT_DIR="$SRC_DIR/build/minified/build"
if [ ! -f "$BUILT_DIR/pdf.min.mjs" ] || [ ! -f "$BUILT_DIR/pdf.worker.min.mjs" ]; then
  echo "error: pdf.js build finished but expected output not found at $BUILT_DIR" >&2
  exit 1
fi

# Replace build-time random UUIDs generated by pdf.js minifier with a static UUID for Reproducible Builds
sed -i -E 's/internal:"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"/internal:"00000000-0000-0000-0000-000000000000"/g' "$BUILT_DIR/pdf.min.mjs" "$BUILT_DIR/pdf.worker.min.mjs" 2>/dev/null || true

mkdir -p "$OUT_DIR"
cp "$BUILT_DIR/pdf.min.mjs" "$BUILT_DIR/pdf.worker.min.mjs" "$OUT_DIR/"

echo "pdf.js ${PDFJS_TAG} built and copied to $OUT_DIR"